/**
 * PDF Footer Component
 * Displays disclaimer and page numbers
 */

import { View, Text, StyleSheet } from "@react-pdf/renderer";
import { FONTS } from "./fonts";

const styles = StyleSheet.create({
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
    borderTopStyle: "solid",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  disclaimer: {
    fontFamily: FONTS.body,
    fontSize: 8,
    color: "#94A3B8",
    maxWidth: "70%",
  },
  branding: {
    fontFamily: FONTS.body,
    fontSize: 8,
    color: "#64748B",
  },
  link: {
    color: "#14B8A6",
  },
});

export function PDFFooter() {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.disclaimer}>
        For informational purposes only. Not medical advice. Consult a
        healthcare provider before starting any supplement regimen.
      </Text>
      <Text style={styles.branding}>
        Generated by <Text style={styles.link}>Vyvata.com</Text>
      </Text>
    </View>
  );
}
