// ══════════════════════════════════════════════════════════
// BATCH 2: Ingredients 273-372 (100 new ingredients)
// Categories: Amino Acids, B-Vitamins, Minerals, Enzymes/Probiotics, 
//             Adaptogens, Polyphenols, Specialized Compounds
// ══════════════════════════════════════════════════════════

export const BATCH_2_INGREDIENTS = [
  
  // ── COMPLETE AMINO ACID SPECTRUM (20) ──────────────────────
  
  {
    name: "Glutamine",
    aliases: ["l-glutamine", "glutamine powder", "gln"],
    category: "amino-acid",
    evidence_tier: "moderate",
    standard_dose_mg: 5000,
    min_dose_mg: 2000,
    max_dose_mg: 30000,
    timing: "post-workout",
    interactions: [],
    synergies: ["Whey Protein", "BCAAs"],
    notes: "Most abundant amino acid in body. Conditionally essential during stress/illness. Evidence for gut barrier function. Muscle recovery benefits weak in healthy athletes.",
    goals: ["recovery", "inflammation", "muscle"],
  },

  {
    name: "Glutamic Acid",
    aliases: ["l-glutamic acid", "glutamate", "glu"],
    category: "amino-acid",
    evidence_tier: "weak",
    standard_dose_mg: 1000,
    min_dose_mg: 500,
    max_dose_mg: 3000,
    timing: "any",
    interactions: [],
    synergies: [],
    notes: "Excitatory neurotransmitter precursor. Non-essential amino acid. Supplementation rarely needed as it's abundant in protein sources. MSG is sodium salt.",
    goals: ["focus"],
  },

  {
    name: "Aspartic Acid",
    aliases: ["l-aspartic acid", "aspartate", "asp"],
    category: "amino-acid",
    evidence_tier: "weak",
    standard_dose_mg: 1000,
    min_dose_mg: 500,
    max_dose_mg: 3000,
    timing: "morning",
    interactions: [],
    synergies: ["D-Aspartic Acid"],
    notes: "Non-essential amino acid. L-form for protein synthesis. Don't confuse with D-Aspartic Acid (DAA) which has different effects on testosterone.",
    goals: ["energy"],
  },

  {
    name: "Asparagine",
    aliases: ["l-asparagine", "asn"],
    category: "amino-acid",
    evidence_tier: "weak",
    standard_dose_mg: 500,
    timing: "any",
    interactions: [],
    synergies: [],
    notes: "Non-essential amino acid named after asparagus. Plays role in protein glycosylation. Supplementation unnecessary for most people.",
    goals: [],
  },

  {
    name: "Alanine",
    aliases: ["l-alanine", "ala"],
    category: "amino-acid",
    evidence_tier: "weak",
    standard_dose_mg: 1000,
    min_dose_mg: 500,
    max_dose_mg: 3000,
    timing: "any",
    interactions: [],
    synergies: ["Beta-Alanine"],
    notes: "Non-essential amino acid involved in glucose-alanine cycle. Distinct from beta-alanine. Rarely supplemented standalone.",
    goals: ["energy"],
  },

  {
    name: "Proline",
    aliases: ["l-proline", "pro"],
    category: "amino-acid",
    evidence_tier: "weak",
    standard_dose_mg: 500,
    min_dose_mg: 250,
    max_dose_mg: 2000,
    timing: "any",
    interactions: [],
    synergies: ["Collagen", "Vitamin C"],
    notes: "Non-essential amino acid crucial for collagen formation. Abundant in collagen supplements. Standalone supplementation uncommon.",
    goals: ["recovery", "longevity"],
  },

  {
    name: "Hydroxyproline",
    aliases: ["l-hydroxyproline", "hyp"],
    category: "amino-acid",
    evidence_tier: "weak",
    standard_dose_mg: 500,
    timing: "any",
    interactions: [],
    synergies: ["Collagen", "Proline", "Vitamin C"],
    notes: "Modified amino acid found exclusively in collagen. Formed from proline via vitamin C-dependent hydroxylation. Marker of collagen synthesis.",
    goals: ["recovery", "longevity"],
  },

  {
    name: "Cysteine",
    aliases: ["l-cysteine", "cys"],
    category: "amino-acid",
    evidence_tier: "moderate",
    standard_dose_mg: 500,
    min_dose_mg: 250,
    max_dose_mg: 1500,
    timing: "any",
    interactions: [],
    synergies: ["NAC", "Glutathione"],
    notes: "Semi-essential sulfur amino acid. Precursor to glutathione. NAC (N-Acetyl-Cysteine) is superior supplemental form with better stability.",
    goals: ["longevity", "recovery"],
  },

  {
    name: "Cystine",
    aliases: ["l-cystine"],
    category: "amino-acid",
    evidence_tier: "weak",
    standard_dose_mg: 300,
    timing: "any",
    interactions: [],
    synergies: ["Cysteine"],
    notes: "Oxidized dimer of two cysteine molecules. Less bioavailable than cysteine or NAC. Rarely supplemented directly.",
    goals: ["recovery"],
  },

  {
    name: "Methionine",
    aliases: ["l-methionine", "met"],
    category: "amino-acid",
    evidence_tier: "moderate",
    standard_dose_mg: 500,
    min_dose_mg: 250,
    max_dose_mg: 2000,
    timing: "morning",
    interactions: [],
    synergies: ["SAMe", "Vitamin B12", "Folate"],
    notes: "Essential sulfur amino acid and methyl donor. Precursor to SAMe. High methionine without adequate B vitamins may raise homocysteine.",
    goals: ["longevity", "focus"],
  },

  {
    name: "Lysine",
    aliases: ["l-lysine", "lys", "lysine hcl"],
    category: "amino-acid",
    evidence_tier: "moderate",
    standard_dose_mg: 1000,
    min_dose_mg: 500,
    max_dose_mg: 3000,
    timing: "any",
    interactions: ["Arginine"],
    synergies: [],
    notes: "Essential amino acid. Competes with arginine absorption. Evidence for HSV suppression and anxiety reduction. Common in protein foods.",
    goals: ["recovery", "inflammation"],
  },

  {
    name: "Threonine",
    aliases: ["l-threonine", "thr"],
    category: "amino-acid",
    evidence_tier: "weak",
    standard_dose_mg: 500,
    min_dose_mg: 250,
    max_dose_mg: 2000,
    timing: "any",
    interactions: [],
    synergies: ["Glycine"],
    notes: "Essential amino acid important for protein structure and glycine production. Rarely deficient or supplemented standalone.",
    goals: ["recovery"],
  },

  {
    name: "Phenylalanine",
    aliases: ["l-phenylalanine", "phe", "dlpa"],
    category: "amino-acid",
    evidence_tier: "moderate",
    standard_dose_mg: 1000,
    min_dose_mg: 500,
    max_dose_mg: 3000,
    timing: "morning",
    interactions: ["MAO inhibitors"],
    synergies: ["L-Tyrosine"],
    notes: "Essential amino acid and tyrosine precursor. DLPA (D,L mix) used for pain and mood. Contraindicated in phenylketonuria (PKU).",
    goals: ["focus", "energy"],
  },

  {
    name: "Tyrosine",
    aliases: ["l-tyrosine", "tyr"],
    category: "amino-acid",
    evidence_tier: "strong",
    standard_dose_mg: 1500,
    min_dose_mg: 500,
    max_dose_mg: 3000,
    timing: "morning",
    interactions: ["MAO inhibitors", "L-Dopa", "Thyroid medications"],
    synergies: ["Caffeine", "Rhodiola Rosea"],
    notes: "Semi-essential amino acid and catecholamine precursor. Enhances cognition under acute stress. NALT (N-Acetyl-L-Tyrosine) has poor conversion.",
    goals: ["focus", "energy"],
  },

  {
    name: "Arginine",
    aliases: ["l-arginine", "arg", "arginine hcl"],
    category: "amino-acid",
    evidence_tier: "moderate",
    standard_dose_mg: 6000,
    min_dose_mg: 3000,
    max_dose_mg: 10000,
    timing: "pre-workout",
    interactions: ["Lysine", "Blood pressure medications"],
    synergies: ["Citrulline"],
    notes: "Semi-essential amino acid and nitric oxide precursor. Poor oral bioavailability due to first-pass metabolism. Citrulline is superior for NO production.",
    goals: ["muscle", "energy", "recovery"],
  },

  {
    name: "Citrulline",
    aliases: ["l-citrulline", "citrulline malate", "cit"],
    category: "amino-acid",
    evidence_tier: "strong",
    standard_dose_mg: 6000,
    min_dose_mg: 3000,
    max_dose_mg: 10000,
    timing: "pre-workout",
    interactions: [],
    synergies: ["Arginine", "Beetroot Extract"],
    notes: "Non-essential amino acid that converts to arginine. Superior to arginine for increasing plasma arginine levels. Citrulline malate adds endurance benefit.",
    goals: ["muscle", "energy", "recovery"],
  },

  {
    name: "Ornithine",
    aliases: ["l-ornithine", "ornithine hcl", "orn"],
    category: "amino-acid",
    evidence_tier: "weak",
    standard_dose_mg: 2000,
    min_dose_mg: 400,
    max_dose_mg: 6000,
    timing: "evening",
    interactions: [],
    synergies: ["Arginine", "Citrulline"],
    notes: "Non-essential amino acid in urea cycle. May reduce fatigue and improve sleep. High doses can cause GI distress.",
    goals: ["sleep", "recovery"],
  },

  {
    name: "Taurine",
    aliases: ["taurine powder", "2-aminoethanesulfonic acid"],
    category: "amino-acid",
    evidence_tier: "strong",
    standard_dose_mg: 2000,
    min_dose_mg: 500,
    max_dose_mg: 6000,
    timing: "pre-workout",
    interactions: [],
    synergies: ["Caffeine", "Magnesium Glycinate"],
    notes: "Conditionally essential sulfonic acid (not true amino acid). Abundant in energy drinks. Supports cardiovascular function, exercise performance, bile conjugation.",
    goals: ["energy", "muscle", "recovery", "longevity"],
  },

  {
    name: "Beta-Alanine",
    aliases: ["β-alanine", "beta alanine", "carnosyn"],
    category: "amino-acid",
    evidence_tier: "strong",
    standard_dose_mg: 3200,
    min_dose_mg: 2400,
    max_dose_mg: 6400,
    timing: "pre-workout",
    interactions: [],
    synergies: ["Creatine Monohydrate", "Carnosine"],
    notes: "Non-proteinogenic amino acid that increases muscle carnosine. Causes harmless tingling (paresthesia). Only useful for 1-4 minute high-intensity efforts.",
    goals: ["muscle", "energy"],
  },

  {
    name: "Carnosine",
    aliases: ["l-carnosine", "beta-alanyl-l-histidine"],
    category: "amino-acid",
    evidence_tier: "moderate",
    standard_dose_mg: 1500,
    min_dose_mg: 500,
    max_dose_mg: 3000,
    timing: "any",
    interactions: [],
    synergies: ["Beta-Alanine", "Zinc"],
    notes: "Dipeptide of beta-alanine and histidine. Beta-alanine supplementation increases muscle carnosine more efficiently. Direct carnosine may benefit aging tissues.",
    goals: ["longevity", "muscle", "recovery"],
  },

  // ── B-VITAMIN COMPLEX (15) ─────────────────────────────────

  {
    name: "Thiamine",
    aliases: ["vitamin b1", "thiamin", "thiamine hcl", "thiamine mononitrate", "b1"],
    category: "vitamin",
    evidence_tier: "strong",
    standard_dose_mg: 1.2,
    min_dose_mg: 1.1,
    max_dose_mg: 100,
    timing: "morning",
    interactions: [],
    synergies: ["Vitamin B12", "Folate", "Magnesium Glycinate"],
    notes: "Water-soluble B vitamin critical for glucose metabolism and nerve function. Deficiency causes beriberi. Benfotiamine is fat-soluble form with better bioavailability.",
    goals: ["energy", "focus"],
  },

  {
    name: "Riboflavin",
    aliases: ["vitamin b2", "b2", "riboflavin-5-phosphate", "r5p"],
    category: "vitamin",
    evidence_tier: "strong",
    standard_dose_mg: 1.3,
    min_dose_mg: 1.1,
    max_dose_mg: 400,
    timing: "morning",
    interactions: [],
    synergies: ["Vitamin B12", "Folate"],
    notes: "Required for FAD/FMN cofactors in energy production. Turns urine bright yellow (harmless). R5P is active form. Evidence for migraine prevention at 400mg.",
    goals: ["energy", "longevity"],
  },

  {
    name: "Niacin",
    aliases: ["vitamin b3", "b3", "nicotinic acid", "niacinamide", "nicotinamide"],
    category: "vitamin",
    evidence_tier: "strong",
    standard_dose_mg: 16,
    min_dose_mg: 14,
    max_dose_mg: 35,
    timing: "morning",
    interactions: ["Statins"],
    synergies: ["NMN", "NR"],
    notes: "NAD+ precursor. Nicotinic acid causes flushing, niacinamide doesn't. High-dose niacin (500mg+) used for cholesterol but has side effects. Stick to RDA unless supervised.",
    goals: ["energy", "longevity"],
  },

  {
    name: "Pantothenic Acid",
    aliases: ["vitamin b5", "b5", "pantothenate", "calcium pantothenate"],
    category: "vitamin",
    evidence_tier: "moderate",
    standard_dose_mg: 5,
    min_dose_mg: 5,
    max_dose_mg: 600,
    timing: "morning",
    interactions: [],
    synergies: ["Vitamin B12", "Folate"],
    notes: "Essential for CoA synthesis and fatty acid metabolism. Name means 'from everywhere' due to wide food distribution. Deficiency extremely rare.",
    goals: ["energy", "recovery"],
  },

  {
    name: "Pyridoxine",
    aliases: ["vitamin b6", "b6", "pyridoxine hcl"],
    category: "vitamin",
    evidence_tier: "strong",
    standard_dose_mg: 1.7,
    min_dose_mg: 1.3,
    max_dose_mg: 100,
    timing: "morning",
    interactions: [],
    synergies: ["Magnesium Glycinate", "Vitamin B12"],
    notes: "Inactive form of B6. Must convert to P5P (active form). High doses (>200mg/day long-term) can cause peripheral neuropathy. P5P preferred.",
    goals: ["energy", "sleep", "focus"],
  },

  {
    name: "Pyridoxal-5-Phosphate",
    aliases: ["p5p", "p-5-p", "active b6", "pyridoxal 5 phosphate"],
    category: "vitamin",
    evidence_tier: "strong",
    standard_dose_mg: 50,
    min_dose_mg: 10,
    max_dose_mg: 100,
    timing: "morning",
    interactions: ["Levodopa"],
    synergies: ["Magnesium Glycinate", "Zinc"],
    notes: "Active form of vitamin B6. Better absorbed than pyridoxine, especially in people with poor conversion. Critical for neurotransmitter synthesis.",
    goals: ["energy", "sleep", "focus"],
  },

  {
    name: "Biotin",
    aliases: ["vitamin b7", "b7", "vitamin h", "d-biotin"],
    category: "vitamin",
    evidence_tier: "moderate",
    standard_dose_mg: 0.03,
    min_dose_mg: 0.03,
    max_dose_mg: 10,
    timing: "morning",
    interactions: [],
    synergies: [],
    notes: "Cofactor for carboxylase enzymes. Popular for hair/skin/nails but evidence weak unless deficient. High doses (>5mg) can interfere with lab tests (troponin, TSH, etc).",
    goals: ["longevity"],
  },

  {
    name: "Folate",
    aliases: ["vitamin b9", "b9", "folic acid", "folacin"],
    category: "vitamin",
    evidence_tier: "strong",
    standard_dose_mg: 0.4,
    min_dose_mg: 0.4,
    max_dose_mg: 1,
    timing: "morning",
    interactions: ["Methotrexate"],
    synergies: ["Vitamin B12", "Vitamin B6"],
    notes: "Generic term for folates. Folic acid is synthetic form requiring conversion. Methylfolate and folinic acid are superior bioactive forms. Critical for DNA synthesis.",
    goals: ["energy", "longevity"],
  },

  {
    name: "Methylfolate",
    aliases: ["5-mthf", "l-methylfolate", "5-methyl-thf", "levomefolic acid", "metafolin"],
    category: "vitamin",
    evidence_tier: "strong",
    standard_dose_mg: 0.4,
    min_dose_mg: 0.4,
    max_dose_mg: 1,
    timing: "morning",
    interactions: [],
    synergies: ["Methylcobalamin", "Vitamin B6"],
    notes: "Active form of folate. Bypasses MTHFR genetic variants. Superior to folic acid for bioavailability. Critical for methylation and homocysteine metabolism.",
    goals: ["energy", "longevity", "focus"],
  },

  {
    name: "5-MTHF",
    aliases: ["5-methyltetrahydrofolate", "active folate"],
    category: "vitamin",
    evidence_tier: "strong",
    standard_dose_mg: 0.4,
    min_dose_mg: 0.4,
    max_dose_mg: 1,
    timing: "morning",
    interactions: [],
    synergies: ["Methylcobalamin", "SAMe"],
    notes: "Same as methylfolate - the biologically active, reduced form of folate. Essential for proper methylation. No conversion needed unlike folic acid.",
    goals: ["energy", "longevity", "focus"],
  },

  {
    name: "Folinic Acid",
    aliases: ["leucovorin", "5-formyl-thf", "calcium folinate"],
    category: "vitamin",
    evidence_tier: "strong",
    standard_dose_mg: 0.4,
    timing: "morning",
    interactions: [],
    synergies: ["Vitamin B12"],
    notes: "Reduced form of folate used medically. One step before 5-MTHF in conversion pathway. Works for people with MTHFR mutations. Prescription in some countries.",
    goals: ["energy", "longevity"],
  },

  {
    name: "Methylcobalamin",
    aliases: ["methyl b12", "methyl cobalamin", "methylb12"],
    category: "vitamin",
    evidence_tier: "strong",
    standard_dose_mg: 0.001,
    min_dose_mg: 0.001,
    max_dose_mg: 5,
    timing: "morning",
    interactions: [],
    synergies: ["Methylfolate", "SAMe"],
    notes: "Methylated form of B12 that directly participates in methylation. Superior to cyanocobalamin. Sublingual absorption bypasses gut issues. Active in CNS.",
    goals: ["energy", "focus", "longevity"],
  },

  {
    name: "Adenosylcobalamin",
    aliases: ["adenosyl b12", "dibencozide", "cobamamide"],
    category: "vitamin",
    evidence_tier: "strong",
    standard_dose_mg: 0.001,
    timing: "morning",
    interactions: [],
    synergies: ["Methylcobalamin"],
    notes: "Mitochondrial form of B12 involved in energy production. Works synergistically with methylcobalamin. Less common but equally important form.",
    goals: ["energy"],
  },

  {
    name: "Hydroxocobalamin",
    aliases: ["hydroxy b12", "hydroxo b12"],
    category: "vitamin",
    evidence_tier: "strong",
    standard_dose_mg: 0.001,
    timing: "morning",
    interactions: [],
    synergies: [],
    notes: "Precursor form of B12 that converts to both methyl- and adenosylcobalamin. Used in injections. Longer retention than cyanocobalamin. Cyanide detoxifier.",
    goals: ["energy", "longevity"],
  },

  {
    name: "Inositol",
    aliases: ["myo-inositol", "inositol powder", "vitamin b8"],
    category: "vitamin",
    evidence_tier: "moderate",
    standard_dose_mg: 2000,
    min_dose_mg: 1000,
    max_dose_mg: 18000,
    timing: "evening",
    interactions: [],
    synergies: ["Choline"],
    notes: "Pseudo-vitamin and signaling molecule. Myo-inositol most common form. Evidence for anxiety, OCD, PCOS, metabolic syndrome. High doses well-tolerated.",
    goals: ["sleep", "focus", "inflammation"],
  },

  // ── MINERALS & TRACE ELEMENTS (20) ────────────────────────

  {
    name: "Calcium",
    aliases: ["calcium carbonate", "calcium citrate", "calcium phosphate", "cal"],
    category: "mineral",
    evidence_tier: "moderate",
    standard_dose_mg: 500,
    min_dose_mg: 200,
    max_dose_mg: 1200,
    timing: "any",
    interactions: ["Iron", "Magnesium Glycinate", "Zinc", "Thyroid medications"],
    synergies: ["Vitamin D3", "Vitamin K2"],
    notes: "Most abundant mineral in body. Citrate form better absorbed than carbonate. Blocks iron absorption - take 4+ hours apart. Split doses for better absorption.",
    goals: ["longevity", "muscle"],
  },

  {
    name: "Phosphorus",
    aliases: ["phosphate", "calcium phosphate"],
    category: "mineral",
    evidence_tier: "weak",
    standard_dose_mg: 700,
    timing: "any",
    interactions: ["Calcium"],
    synergies: [],
    notes: "Second most abundant mineral. Critical for ATP and bone health. Almost never needs supplementation - abundant in diet. Excess phosphorus (sodas) problematic.",
    goals: [],
  },

  {
    name: "Potassium",
    aliases: ["potassium citrate", "potassium chloride", "potassium gluconate", "k"],
    category: "mineral",
    evidence_tier: "strong",
    standard_dose_mg: 3500,
    min_dose_mg: 2600,
    max_dose_mg: 4700,
    timing: "any",
    interactions: ["ACE inhibitors", "Potassium-sparing diuretics", "NSAIDs"],
    synergies: ["Magnesium Glycinate", "Sodium"],
    notes: "Critical electrolyte. FDA limits supplements to 99mg per dose. Get from food (bananas, potatoes, spinach). High doses dangerous for people with kidney disease.",
    goals: ["energy", "muscle", "recovery"],
  },

  {
    name: "Sodium",
    aliases: ["sodium chloride", "salt", "na"],
    category: "mineral",
    evidence_tier: "strong",
    standard_dose_mg: 2300,
    timing: "any",
    interactions: ["Blood pressure medications"],
    synergies: ["Potassium", "Chloride"],
    notes: "Essential electrolyte often over-consumed. Athletes and low-carb dieters may need extra. Balance with potassium important. Most people get enough from food.",
    goals: ["energy", "muscle"],
  },

  {
    name: "Chloride",
    aliases: ["sodium chloride", "cl"],
    category: "mineral",
    evidence_tier: "weak",
    standard_dose_mg: 2300,
    timing: "any",
    interactions: [],
    synergies: ["Sodium"],
    notes: "Essential electrolyte and major anion. Obtained from salt. Rarely needs standalone supplementation. Critical for stomach acid production and fluid balance.",
    goals: [],
  },

  {
    name: "Sulfur",
    aliases: ["msm", "methylsulfonylmethane", "organic sulfur"],
    category: "mineral",
    evidence_tier: "moderate",
    standard_dose_mg: 3000,
    min_dose_mg: 1500,
    max_dose_mg: 6000,
    timing: "any",
    interactions: [],
    synergies: ["Glucosamine", "Chondroitin"],
    notes: "Essential element obtained from sulfur amino acids and MSM. MSM is popular organic sulfur supplement for joint health. Modest anti-inflammatory evidence.",
    goals: ["recovery", "inflammation"],
  },

  {
    name: "Chromium",
    aliases: ["chromium picolinate", "chromium polynicotinate", "gtf chromium", "cr"],
    category: "mineral",
    evidence_tier: "moderate",
    standard_dose_mg: 0.2,
    min_dose_mg: 0.035,
    max_dose_mg: 1,
    timing: "with-food",
    interactions: ["Diabetes medications"],
    synergies: ["Berberine", "Alpha Lipoic Acid"],
    notes: "Trace mineral that enhances insulin signaling. Picolinate form most studied. May improve glucose control in diabetics. Evidence mixed for weight loss.",
    goals: ["longevity", "energy"],
  },

  {
    name: "Molybdenum",
    aliases: ["molybdenum glycinate", "mo"],
    category: "mineral",
    evidence_tier: "weak",
    standard_dose_mg: 0.045,
    min_dose_mg: 0.045,
    max_dose_mg: 2,
    timing: "any",
    interactions: ["Copper"],
    synergies: [],
    notes: "Trace mineral cofactor for sulfite oxidase and other enzymes. Deficiency extremely rare. Usually unnecessary to supplement unless specific medical need.",
    goals: [],
  },

  {
    name: "Selenium",
    aliases: ["selenium yeast", "selenomethionine", "sodium selenite", "se"],
    category: "mineral",
    evidence_tier: "moderate",
    standard_dose_mg: 0.2,
    min_dose_mg: 0.055,
    max_dose_mg: 0.4,
    timing: "any",
    interactions: [],
    synergies: ["Vitamin E", "Iodine"],
    notes: "Essential trace element for selenoproteins (glutathione peroxidase, etc). Narrow therapeutic window - toxicity above 400mcg/day. Selenomethionine better absorbed.",
    goals: ["longevity", "inflammation"],
  },

  {
    name: "Iodine",
    aliases: ["potassium iodide", "kelp", "nascent iodine", "i"],
    category: "mineral",
    evidence_tier: "moderate",
    standard_dose_mg: 0.15,
    min_dose_mg: 0.15,
    max_dose_mg: 1.1,
    timing: "any",
    interactions: ["Thyroid medications"],
    synergies: ["Selenium"],
    notes: "Essential for thyroid hormone synthesis. Deficiency still common globally. Iodized salt sufficient for most. High doses can suppress thyroid function.",
    goals: ["energy", "longevity"],
  },

  {
    name: "Manganese",
    aliases: ["manganese bisglycinate", "manganese citrate", "manganese gluconate", "mn"],
    category: "mineral",
    evidence_tier: "moderate",
    standard_dose_mg: 2.3,
    min_dose_mg: 1.8,
    max_dose_mg: 11,
    timing: "any",
    interactions: ["Iron", "Calcium"],
    synergies: ["Vitamin K2"],
    notes: "Trace element for antioxidant enzymes and bone health. Competes with iron absorption. Toxicity possible above 11mg/day. Most get enough from diet.",
    goals: ["longevity"],
  },

  {
    name: "Silicon",
    aliases: ["silica", "silicon dioxide", "orthosilicic acid", "ch-osa", "si"],
    category: "mineral",
    evidence_tier: "weak",
    standard_dose_mg: 10,
    min_dose_mg: 5,
    max_dose_mg: 50,
    timing: "any",
    interactions: [],
    synergies: ["Collagen", "Vitamin C"],
    notes: "Trace element for connective tissue. Evidence very limited. Choline-stabilized orthosilicic acid (ch-OSA) is bioavailable form. May support bone/skin/hair.",
    goals: ["longevity", "recovery"],
  },

  {
    name: "Vanadium",
    aliases: ["vanadyl sulfate", "vanadium sulfate", "v"],
    category: "mineral",
    evidence_tier: "weak",
    standard_dose_mg: 0.05,
    max_dose_mg: 1.8,
    timing: "with-food",
    interactions: ["Diabetes medications"],
    synergies: [],
    notes: "Trace element with insulin-mimetic properties. Very limited human evidence. GI side effects common. Not recommended for general use.",
    goals: [],
  },

  {
    name: "Strontium",
    aliases: ["strontium citrate", "strontium ranelate", "sr"],
    category: "mineral",
    evidence_tier: "weak",
    standard_dose_mg: 680,
    timing: "bedtime",
    interactions: ["Calcium", "Bisphosphonates"],
    synergies: ["Calcium", "Vitamin D3"],
    notes: "Trace element similar to calcium. Strontium ranelate prescription drug for osteoporosis (EU). Citrate form available as supplement. Competes with calcium absorption.",
    goals: ["longevity"],
  },

  {
    name: "Lithium",
    aliases: ["lithium orotate", "lithium aspartate", "li"],
    category: "mineral",
    evidence_tier: "weak",
    standard_dose_mg: 5,
    min_dose_mg: 1,
    max_dose_mg: 20,
    timing: "evening",
    interactions: ["Prescription lithium", "NSAIDs"],
    synergies: [],
    notes: "Trace element at low doses vs prescription carbonate (300-900mg elemental). May support mood and neuroprotection. Safety of long-term supplementation unclear.",
    goals: ["focus", "longevity"],
  },

  {
    name: "Germanium",
    aliases: ["germanium-132", "ge-132", "organic germanium"],
    category: "mineral",
    evidence_tier: "weak",
    standard_dose_mg: 50,
    max_dose_mg: 150,
    timing: "any",
    interactions: [],
    synergies: [],
    notes: "Trace element with limited evidence. Ge-132 (carboxyethyl germanium sesquioxide) is organic form. Inorganic forms toxic. Controversial supplement.",
    goals: [],
  },

  {
    name: "Rubidium",
    aliases: ["rb"],
    category: "mineral",
    evidence_tier: "weak",
    timing: "any",
    interactions: [],
    synergies: [],
    notes: "Alkali metal similar to potassium. Experimental antidepressant in animals. No established human dose or safety data. Not recommended for supplementation.",
    goals: [],
  },

  {
    name: "Cesium",
    aliases: ["cs"],
    category: "mineral",
    evidence_tier: "weak",
    timing: "any",
    interactions: [],
    synergies: [],
    notes: "Alkali metal with no known biological function. Used in alternative cancer treatments without evidence. Can cause dangerous electrolyte imbalances. Avoid.",
    goals: [],
  },

  {
    name: "Nickel",
    aliases: ["ni"],
    category: "mineral",
    evidence_tier: "weak",
    timing: "any",
    interactions: [],
    synergies: [],
    notes: "Trace element with unclear essential role in humans. Most people get enough from diet. Can cause allergic reactions. Supplementation not recommended.",
    goals: [],
  },

  {
    name: "Tin",
    aliases: ["sn"],
    category: "mineral",
    evidence_tier: "weak",
    timing: "any",
    interactions: [],
    synergies: [],
    notes: "Trace element with no established biological function in humans. Found in food but not considered essential. No basis for supplementation.",
    goals: [],
  },

  // ── DIGESTIVE ENZYMES & PROBIOTICS (15) ────────────────────

  {
    name: "Amylase",
    aliases: ["alpha-amylase", "pancreatic amylase"],
    category: "enzyme",
    evidence_tier: "moderate",
    standard_dose_mg: 15000,
    timing: "with-meals",
    interactions: [],
    synergies: ["Protease", "Lipase"],
    notes: "Digestive enzyme that breaks down starches and carbohydrates. Produced by pancreas and saliva. Supplementation helps carbohydrate maldigestion.",
    goals: ["inflammation", "energy"],
  },

  {
    name: "Protease",
    aliases: ["pancreatic protease", "proteolytic enzymes"],
    category: "enzyme",
    evidence_tier: "moderate",
    standard_dose_mg: 40000,
    timing: "with-meals",
    interactions: ["Anticoagulants"],
    synergies: ["Amylase", "Lipase"],
    notes: "Digestive enzymes that break down proteins. Include pepsin, trypsin, chymotrypsin. When taken between meals may have anti-inflammatory effects.",
    goals: ["inflammation", "recovery"],
  },

  {
    name: "Lipase",
    aliases: ["pancreatic lipase"],
    category: "enzyme",
    evidence_tier: "moderate",
    standard_dose_mg: 8000,
    timing: "with-meals",
    interactions: [],
    synergies: ["Amylase", "Protease", "Ox Bile"],
    notes: "Digestive enzyme that breaks down fats. Produced by pancreas. Essential for fat-soluble vitamin absorption. Pancreatic insufficiency benefits most.",
    goals: ["energy", "longevity"],
  },

  {
    name: "Cellulase",
    aliases: ["cellulase enzyme"],
    category: "enzyme",
    evidence_tier: "weak",
    standard_dose_mg: 1000,
    timing: "with-meals",
    interactions: [],
    synergies: ["Amylase"],
    notes: "Enzyme that breaks down cellulose (plant fiber). Humans don't produce this. May reduce gas and bloating from vegetables. Evidence limited.",
    goals: ["inflammation"],
  },

  {
    name: "Lactase",
    aliases: ["lactase enzyme", "beta-galactosidase"],
    category: "enzyme",
    evidence_tier: "strong",
    standard_dose_mg: 9000,
    timing: "with-dairy",
    interactions: [],
    synergies: [],
    notes: "Enzyme that breaks down lactose (milk sugar). Deficiency causes lactose intolerance. Highly effective supplementation before dairy consumption.",
    goals: ["inflammation"],
  },

  {
    name: "Bromelain",
    aliases: ["bromelain enzyme", "pineapple enzyme"],
    category: "enzyme",
    evidence_tier: "moderate",
    standard_dose_mg: 500,
    min_dose_mg: 200,
    max_dose_mg: 2000,
    timing: "any",
    interactions: ["Anticoagulants", "Antibiotics"],
    synergies: ["Quercetin", "Turmeric"],
    notes: "Proteolytic enzyme from pineapple. Anti-inflammatory when taken on empty stomach. Digestive aid when taken with meals. Enhances quercetin absorption.",
    goals: ["inflammation", "recovery"],
  },

  {
    name: "Papain",
    aliases: ["papaya enzyme", "papaya protease"],
    category: "enzyme",
    evidence_tier: "moderate",
    standard_dose_mg: 100,
    timing: "with-meals",
    interactions: ["Anticoagulants"],
    synergies: ["Bromelain"],
    notes: "Proteolytic enzyme from papaya. Aids protein digestion and has anti-inflammatory properties. Often combined with bromelain in digestive formulas.",
    goals: ["inflammation", "recovery"],
  },

  {
    name: "Pepsin",
    aliases: ["pepsin enzyme"],
    category: "enzyme",
    evidence_tier: "weak",
    standard_dose_mg: 100,
    timing: "with-meals",
    interactions: [],
    synergies: ["Betaine HCl"],
    notes: "Stomach enzyme that digests proteins. Active in acidic pH. Supplementation most useful with betaine HCl for low stomach acid.",
    goals: ["inflammation"],
  },

  {
    name: "Pancreatin",
    aliases: ["pancreatic enzymes", "pancrelipase"],
    category: "enzyme",
    evidence_tier: "strong",
    standard_dose_mg: 500,
    timing: "with-meals",
    interactions: [],
    synergies: [],
    notes: "Mixture of pancreatic enzymes (amylase, protease, lipase). Prescription strength for pancreatic insufficiency. OTC supplements weaker but may help digestion.",
    goals: ["inflammation", "energy"],
  },

  {
    name: "Ox Bile",
    aliases: ["bile salts", "bovine bile", "ox bile extract"],
    category: "enzyme",
    evidence_tier: "moderate",
    standard_dose_mg: 500,
    min_dose_mg: 125,
    max_dose_mg: 1000,
    timing: "with-fatty-meals",
    interactions: [],
    synergies: ["Lipase"],
    notes: "Contains bile acids that emulsify fats. Useful for people without gallbladder or with bile insufficiency. Helps fat-soluble vitamin absorption.",
    goals: ["energy", "longevity"],
  },

  {
    name: "Betaine HCl",
    aliases: ["betaine hydrochloride", "betaine hcl with pepsin"],
    category: "enzyme",
    evidence_tier: "moderate",
    standard_dose_mg: 650,
    min_dose_mg: 325,
    max_dose_mg: 1950,
    timing: "with-protein-meals",
    interactions: ["NSAIDs", "Aspirin"],
    synergies: ["Pepsin"],
    notes: "Supplemental stomach acid. Useful for hypochlorhydria (low stomach acid). Start low dose and titrate. Avoid with ulcers or NSAID use.",
    goals: ["inflammation", "energy"],
  },

  {
    name: "Saccharomyces Boulardii",
    aliases: ["s boulardii", "s boulardii lyo", "florastor", "saccharomyces boulardii"],
    category: "probiotic",
    evidence_tier: "strong",
    standard_dose_mg: 5000000000,
    min_dose_mg: 5000000000,
    max_dose_mg: 20000000000,
    timing: "any",
    interactions: ["Antifungals"],
    synergies: ["Lactobacillus rhamnosus GG"],
    notes: "Beneficial yeast probiotic. Prevents C. diff and antibiotic-associated diarrhea. Can be taken WITH antibiotics. Avoid with antifungal medications.",
    goals: ["inflammation", "recovery"],
  },

  {
    name: "Lactobacillus Rhamnosus",
    aliases: ["l rhamnosus", "l rhamnosus gg", "lgg"],
    category: "probiotic",
    evidence_tier: "strong",
    standard_dose_mg: 10000000000,
    min_dose_mg: 1000000000,
    max_dose_mg: 100000000000,
    timing: "morning",
    interactions: [],
    synergies: ["Bifidobacterium longum", "Inulin"],
    notes: "Most researched probiotic strain. LGG strain has 1000+ studies. Survives stomach acid. Evidence for IBS, anxiety, immune support, diarrhea prevention.",
    goals: ["inflammation", "energy", "focus"],
  },

  {
    name: "Bifidobacterium Longum",
    aliases: ["b longum", "bifidobacterium longum 1714", "b longum 35624"],
    category: "probiotic",
    evidence_tier: "strong",
    standard_dose_mg: 1000000000,
    min_dose_mg: 1000000000,
    max_dose_mg: 10000000000,
    timing: "evening",
    interactions: [],
    synergies: ["Lactobacillus rhamnosus GG", "Inulin"],
    notes: "Specific strain 1714 reduces stress and anxiety via gut-brain axis. Strain 35624 effective for IBS. Requires prebiotic fiber for colonization.",
    goals: ["sleep", "inflammation", "focus"],
  },

  {
    name: "Bacillus Coagulans",
    aliases: ["bacillus coagulans", "lactobacillus sporogenes", "bc30"],
    category: "probiotic",
    evidence_tier: "moderate",
    standard_dose_mg: 2000000000,
    min_dose_mg: 1000000000,
    max_dose_mg: 6000000000,
    timing: "any",
    interactions: [],
    synergies: [],
    notes: "Spore-forming probiotic with excellent shelf stability. BC30 is trademarked strain. Evidence for IBS and immune function. Heat and acid resistant.",
    goals: ["inflammation", "recovery"],
  },

  // ── HERBAL ADAPTOGENS & BOTANICALS (20) ───────────────────

  {
    name: "Holy Basil",
    aliases: ["tulsi", "ocimum sanctum", "ocimum tenuiflorum"],
    category: "adaptogen",
    evidence_tier: "moderate",
    standard_dose_mg: 500,
    min_dose_mg: 300,
    max_dose_mg: 2000,
    timing: "evening",
    interactions: ["Diabetes medications"],
    synergies: ["Ashwagandha"],
    notes: "Ayurvedic adaptogen with anti-stress properties. May lower blood sugar. Standardize to 2.5% ursolic acid. Calming adaptogen suitable for evening.",
    goals: ["sleep", "inflammation", "recovery"],
  },

  {
    name: "Reishi",
    aliases: ["ganoderma lucidum", "ganoderma", "reishi mushroom", "lingzhi"],
    category: "mushroom",
    evidence_tier: "moderate",
    standard_dose_mg: 1500,
    min_dose_mg: 1000,
    max_dose_mg: 5000,
    timing: "evening",
    interactions: ["Warfarin", "Immunosuppressants"],
    synergies: ["Turkey Tail", "Chaga"],
    notes: "Calming medicinal mushroom. Immune modulation and sleep support. Triterpenes and polysaccharides are active compounds. Extract preferred over raw powder.",
    goals: ["sleep", "inflammation", "longevity", "recovery"],
  },

  {
    name: "Chaga",
    aliases: ["inonotus obliquus", "chaga mushroom"],
    category: "mushroom",
    evidence_tier: "weak",
    standard_dose_mg: 2000,
    min_dose_mg: 500,
    max_dose_mg: 3000,
    timing: "morning",
    interactions: ["Warfarin", "Diabetes medications"],
    synergies: ["Reishi"],
    notes: "Medicinal mushroom with very high antioxidant content (ORAC). Most evidence is in vitro. May potentiate anticoagulants. Quality varies widely.",
    goals: ["longevity", "inflammation"],
  },

  {
    name: "Turkey Tail",
    aliases: ["trametes versicolor", "coriolus versicolor", "psp", "psk"],
    category: "mushroom",
    evidence_tier: "moderate",
    standard_dose_mg: 3000,
    min_dose_mg: 1000,
    max_dose_mg: 9000,
    timing: "any",
    interactions: [],
    synergies: ["Reishi", "Lion's Mane"],
    notes: "PSP and PSK extracts used in Asian cancer therapy. Immune modulation via beta-glucans. Full-spectrum extract preferred. Standardize to polysaccharides.",
    goals: ["longevity", "inflammation", "recovery"],
  },

  {
    name: "Maitake",
    aliases: ["grifola frondosa", "maitake mushroom", "d-fraction"],
    category: "mushroom",
    evidence_tier: "moderate",
    standard_dose_mg: 3000,
    min_dose_mg: 1000,
    max_dose_mg: 7000,
    timing: "any",
    interactions: ["Diabetes medications"],
    synergies: ["Shiitake", "Reishi"],
    notes: "Medicinal mushroom rich in D-fraction beta-glucans. May lower blood glucose. Immune modulating. Standardize to polysaccharides (>30%).",
    goals: ["longevity", "inflammation"],
  },

  {
    name: "Shiitake",
    aliases: ["lentinula edodes", "lentinan", "shiitake mushroom"],
    category: "mushroom",
    evidence_tier: "moderate",
    standard_dose_mg: 1500,
    min_dose_mg: 1000,
    max_dose_mg: 5000,
    timing: "any",
    interactions: [],
    synergies: ["Reishi", "Maitake"],
    notes: "Common culinary mushroom with medicinal properties. Lentinan polysaccharide supports immune function. Modest evidence for cholesterol reduction.",
    goals: ["longevity", "inflammation"],
  },

  {
    name: "He Shou Wu",
    aliases: ["fo-ti", "polygonum multiflorum", "flowery knotweed"],
    category: "adaptogen",
    evidence_tier: "weak",
    standard_dose_mg: 1000,
    min_dose_mg: 500,
    max_dose_mg: 3000,
    timing: "morning",
    interactions: ["Warfarin", "Estrogen"],
    synergies: [],
    notes: "Traditional Chinese longevity herb. Hepatotoxicity risk with raw form. Processed (prepared) form preferred. Limited modern clinical evidence.",
    goals: ["longevity", "energy"],
  },

  {
    name: "Schisandra",
    aliases: ["schisandra chinensis", "five flavor berry", "wu wei zi"],
    category: "adaptogen",
    evidence_tier: "moderate",
    standard_dose_mg: 500,
    min_dose_mg: 250,
    max_dose_mg: 3000,
    timing: "morning",
    interactions: [],
    synergies: ["Rhodiola Rosea"],
    notes: "Adaptogen with hepatoprotective properties. Stimulating - take in morning. Standardize to schisandrins. Used for mental and physical performance.",
    goals: ["energy", "focus", "longevity"],
  },

  {
    name: "Eleuthero",
    aliases: ["siberian ginseng", "eleutherococcus senticosus"],
    category: "adaptogen",
    evidence_tier: "moderate",
    standard_dose_mg: 300,
    min_dose_mg: 150,
    max_dose_mg: 1200,
    timing: "morning",
    interactions: ["Diabetes medications"],
    synergies: [],
    notes: "Not true ginseng but related adaptogen. Standardize to eleutherosides (>0.8%). Endurance and immune support. Stimulating nature.",
    goals: ["energy", "recovery"],
  },

  {
    name: "Jiaogulan",
    aliases: ["gynostemma pentaphyllum", "southern ginseng", "immortality herb"],
    category: "adaptogen",
    evidence_tier: "weak",
    standard_dose_mg: 450,
    min_dose_mg: 225,
    max_dose_mg: 900,
    timing: "any",
    interactions: ["Immunosuppressants"],
    synergies: [],
    notes: "Adaptogen containing gypenosides similar to ginseng saponins. Traditional longevity herb. Limited rigorous human trials.",
    goals: ["longevity", "energy"],
  },

  {
    name: "Gynostemma",
    aliases: ["gynostemma pentaphyllum", "jiaogulan"],
    category: "adaptogen",
    evidence_tier: "weak",
    standard_dose_mg: 450,
    timing: "any",
    interactions: [],
    synergies: [],
    notes: "Same as Jiaogulan - added as alias entry. Adaptogen with gypenosides. May support metabolic health and longevity.",
    goals: ["longevity", "energy"],
  },

  {
    name: "Suma",
    aliases: ["pfaffia paniculata", "brazilian ginseng"],
    category: "adaptogen",
    evidence_tier: "weak",
    standard_dose_mg: 500,
    timing: "morning",
    interactions: [],
    synergies: [],
    notes: "South American adaptogen. Contains ecdysterones. Traditional energy and immune tonic. Very limited modern research.",
    goals: ["energy", "recovery"],
  },

  {
    name: "Astragalus",
    aliases: ["astragalus membranaceus", "huang qi"],
    category: "adaptogen",
    evidence_tier: "moderate",
    standard_dose_mg: 1000,
    min_dose_mg: 500,
    max_dose_mg: 4000,
    timing: "morning",
    interactions: ["Immunosuppressants"],
    synergies: ["Reishi"],
    notes: "Traditional Chinese immune tonic. Polysaccharides and saponins are active. Avoid during acute infection. May support telomerase activity.",
    goals: ["longevity", "energy", "recovery"],
  },

  {
    name: "Gotu Kola",
    aliases: ["centella asiatica", "brahmi", "indian pennywort"],
    category: "nootropic",
    evidence_tier: "weak",
    standard_dose_mg: 750,
    min_dose_mg: 500,
    max_dose_mg: 2000,
    timing: "morning",
    interactions: ["Sedatives", "Hepatotoxic drugs"],
    synergies: [],
    notes: "Not same as Bacopa (also called brahmi). Adaptogenic herb for cognition and wound healing. Evidence limited but traditional use extensive.",
    goals: ["focus", "recovery", "longevity"],
  },

  {
    name: "Brahmi",
    aliases: ["bacopa monnieri"],
    category: "nootropic",
    evidence_tier: "moderate",
    standard_dose_mg: 300,
    timing: "morning",
    interactions: [],
    synergies: [],
    notes: "Same as Bacopa Monnieri (already in database). Added here as it's sometimes called Brahmi. Takes 8-12 weeks for cognitive effects.",
    goals: ["focus", "longevity"],
  },

  {
    name: "Mucuna Pruriens",
    aliases: ["mucuna", "velvet bean", "l-dopa", "kapikachhu"],
    category: "nootropic",
    evidence_tier: "moderate",
    standard_dose_mg: 500,
    min_dose_mg: 250,
    max_dose_mg: 1000,
    timing: "morning",
    interactions: ["MAO inhibitors", "Antidepressants", "Antipsychotics"],
    synergies: [],
    notes: "Natural L-DOPA source (4-7% in standardized extracts). Enhances dopamine levels. Can deplete dopamine with chronic use. Cycle on/off recommended.",
    goals: ["focus", "energy"],
  },

  {
    name: "Pine Pollen",
    aliases: ["pinus massoniana", "pine pollen powder"],
    category: "adaptogen",
    evidence_tier: "weak",
    standard_dose_mg: 1000,
    timing: "morning",
    interactions: [],
    synergies: [],
    notes: "Contains plant sterols and claimed phytoandrogens. Evidence for testosterone boost is weak. Nutritionally dense but hormonal effects unproven.",
    goals: ["energy"],
  },

  {
    name: "Shilajit",
    aliases: ["mumie", "mineral pitch", "salajeet"],
    category: "adaptogen",
    evidence_tier: "moderate",
    standard_dose_mg: 300,
    min_dose_mg: 150,
    max_dose_mg: 500,
    timing: "morning",
    interactions: [],
    synergies: ["CoQ10", "Ashwagandha"],
    notes: "Himalayan resin rich in fulvic acid and minerals. Enhances CoQ10 effectiveness. May support testosterone and mitochondrial function. Quality varies widely.",
    goals: ["longevity", "energy", "muscle"],
  },

  {
    name: "Cistanche",
    aliases: ["cistanche tubulosa", "desert ginseng", "rou cong rong"],
    category: "adaptogen",
    evidence_tier: "weak",
    standard_dose_mg: 400,
    min_dose_mg: 200,
    max_dose_mg: 1000,
    timing: "morning",
    interactions: [],
    synergies: [],
    notes: "Traditional Chinese herb for kidney yang deficiency. Phenylethanoid glycosides are active. May support testosterone and cognitive function. Limited modern research.",
    goals: ["energy", "longevity"],
  },

  {
    name: "Moringa",
    aliases: ["moringa oleifera", "drumstick tree", "horseradish tree"],
    category: "plant-extract",
    evidence_tier: "moderate",
    standard_dose_mg: 2000,
    min_dose_mg: 1000,
    max_dose_mg: 8000,
    timing: "morning",
    interactions: ["Diabetes medications"],
    synergies: ["Spirulina"],
    notes: "Nutrient-dense superfood rich in vitamins, minerals, isothiocyanates. May lower blood glucose. Leaf powder preferred over extract for full spectrum.",
    goals: ["energy", "longevity", "inflammation"],
  },

  // ── POLYPHENOLS & FLAVONOIDS (10) ─────────────────────────

  {
    name: "Hesperidin",
    aliases: ["hesperidin", "citrus bioflavonoid"],
    category: "antioxidant",
    evidence_tier: "moderate",
    standard_dose_mg: 500,
    min_dose_mg: 150,
    max_dose_mg: 1000,
    timing: "any",
    interactions: [],
    synergies: ["Vitamin C", "Quercetin", "Diosmin"],
    notes: "Citrus flavonoid with vascular benefits. Evidence for reducing blood pressure and inflammation. Often combined with diosmin (2:1 ratio) for venous insufficiency.",
    goals: ["longevity", "inflammation"],
  },

  {
    name: "Rutin",
    aliases: ["rutoside", "quercetin rutinoside", "vitamin p"],
    category: "antioxidant",
    evidence_tier: "moderate",
    standard_dose_mg: 500,
    min_dose_mg: 250,
    max_dose_mg: 1000,
    timing: "any",
    interactions: ["Anticoagulants"],
    synergies: ["Quercetin", "Vitamin C"],
    notes: "Quercetin glycoside from buckwheat and citrus. Antioxidant with vascular benefits. May strengthen capillaries and reduce edema.",
    goals: ["longevity", "inflammation"],
  },

  {
    name: "Diosmin",
    aliases: ["diosmin", "diosmetin"],
    category: "antioxidant",
    evidence_tier: "moderate",
    standard_dose_mg: 450,
    min_dose_mg: 450,
    max_dose_mg: 900,
    timing: "any",
    interactions: [],
    synergies: ["Hesperidin"],
    notes: "Citrus flavonoid used for venous insufficiency. Often combined with hesperidin in 1:2 ratio (Daflon formula). Prescription drug in some countries.",
    goals: ["inflammation", "recovery"],
  },

  {
    name: "Naringenin",
    aliases: ["naringenin", "naringin"],
    category: "antioxidant",
    evidence_tier: "moderate",
    standard_dose_mg: 100,
    min_dose_mg: 50,
    max_dose_mg: 300,
    timing: "any",
    interactions: ["CYP3A4 substrates"],
    synergies: ["Hesperidin"],
    notes: "Grapefruit flavonoid with metabolic benefits. Naringin is glycoside, naringenin is aglycone. May inhibit CYP3A4 (grapefruit juice effect).",
    goals: ["longevity", "inflammation"],
  },

  {
    name: "Tangeretin",
    aliases: ["tangeretin"],
    category: "antioxidant",
    evidence_tier: "weak",
    standard_dose_mg: 100,
    timing: "any",
    interactions: [],
    synergies: ["Nobiletin"],
    notes: "Citrus polymethoxyflavone from tangerine peel. May have neuroprotective and anti-inflammatory effects. Limited human research.",
    goals: ["longevity", "inflammation"],
  },

  {
    name: "Nobiletin",
    aliases: ["nobiletin"],
    category: "antioxidant",
    evidence_tier: "weak",
    standard_dose_mg: 100,
    timing: "any",
    interactions: [],
    synergies: ["Tangeretin"],
    notes: "Citrus polymethoxyflavone with promising preclinical data for neuroprotection and metabolism. Very limited human trials.",
    goals: ["longevity", "focus"],
  },

  {
    name: "Baicalein",
    aliases: ["baicalein", "baicalin"],
    category: "antioxidant",
    evidence_tier: "moderate",
    standard_dose_mg: 100,
    min_dose_mg: 50,
    max_dose_mg: 300,
    timing: "any",
    interactions: [],
    synergies: ["Wogonin"],
    notes: "Flavonoid from Scutellaria baicalensis (Chinese skullcap). Baicalin is glycoside, baicalein is aglycone. Anti-inflammatory and neuroprotective properties.",
    goals: ["inflammation", "longevity"],
  },

  {
    name: "Wogonin",
    aliases: ["wogonin"],
    category: "antioxidant",
    evidence_tier: "weak",
    standard_dose_mg: 100,
    timing: "any",
    interactions: [],
    synergies: ["Baicalein"],
    notes: "Flavonoid from Scutellaria species. May have anxiolytic and anti-inflammatory effects. Limited human research.",
    goals: ["sleep", "inflammation"],
  },

  {
    name: "Chrysin",
    aliases: ["chrysin", "5,7-dihydroxyflavone"],
    category: "antioxidant",
    evidence_tier: "weak",
    standard_dose_mg: 500,
    min_dose_mg: 250,
    max_dose_mg: 1500,
    timing: "any",
    interactions: [],
    synergies: [],
    notes: "Flavonoid claimed to inhibit aromatase and boost testosterone. Poor oral bioavailability limits effectiveness. Human evidence for hormonal effects lacking.",
    goals: ["muscle"],
  },

  {
    name: "Catechin",
    aliases: ["catechins", "epigallocatechin", "green tea catechins"],
    category: "antioxidant",
    evidence_tier: "moderate",
    standard_dose_mg: 200,
    min_dose_mg: 100,
    max_dose_mg: 800,
    timing: "morning",
    interactions: ["Iron"],
    synergies: ["EGCG", "Caffeine"],
    notes: "Polyphenol class from tea. EGCG is most studied catechin. Antioxidant benefits. Take between meals to avoid iron absorption inhibition.",
    goals: ["longevity", "inflammation"],
  },

  // ── SPECIALIZED COMPOUNDS (10) ─────────────────────────────

  {
    name: "SAMe",
    aliases: ["s-adenosyl-l-methionine", "s-adenosylmethionine", "same supplement"],
    category: "nootropic",
    evidence_tier: "strong",
    standard_dose_mg: 800,
    min_dose_mg: 400,
    max_dose_mg: 1600,
    timing: "morning",
    interactions: ["SSRIs", "MAO inhibitors"],
    synergies: ["Vitamin B12", "Folate", "Methylfolate"],
    notes: "Universal methyl donor. Strong evidence for depression (comparable to SSRIs) and osteoarthritis. Expensive. Take on empty stomach. Risk of mania in bipolar.",
    goals: ["focus", "recovery", "inflammation"],
  },

  {
    name: "TMG",
    aliases: ["trimethylglycine", "betaine", "betaine anhydrous"],
    category: "amino-acid",
    evidence_tier: "moderate",
    standard_dose_mg: 2500,
    min_dose_mg: 1250,
    max_dose_mg: 6000,
    timing: "pre-workout",
    interactions: [],
    synergies: ["Creatine Monohydrate", "SAMe"],
    notes: "Methyl donor and osmolyte. Evidence for power output and body composition. Lowers homocysteine. Supports methylation pathways.",
    goals: ["muscle", "recovery", "longevity"],
  },

  {
    name: "Choline",
    aliases: ["choline bitartrate", "choline chloride"],
    category: "nootropic",
    evidence_tier: "moderate",
    standard_dose_mg: 500,
    min_dose_mg: 250,
    max_dose_mg: 3000,
    timing: "any",
    interactions: [],
    synergies: ["Inositol"],
    notes: "Essential nutrient and acetylcholine precursor. Bitartrate form has poor brain bioavailability. Alpha-GPC and CDP-choline superior for cognition.",
    goals: ["focus", "longevity"],
  },

  {
    name: "CDP-Choline",
    aliases: ["citicoline", "cdp choline"],
    category: "nootropic",
    evidence_tier: "moderate",
    standard_dose_mg: 500,
    min_dose_mg: 250,
    max_dose_mg: 1000,
    timing: "morning",
    interactions: [],
    synergies: ["Alpha-GPC"],
    notes: "Choline source that also provides cytidine. Good for cognition but redundant with Alpha-GPC. May support dopamine systems.",
    goals: ["focus"],
  },

  {
    name: "GPC",
    aliases: ["alpha-gpc", "choline alphoscerate", "alpha glycerophosphocholine"],
    category: "nootropic",
    evidence_tier: "moderate",
    standard_dose_mg: 600,
    min_dose_mg: 300,
    max_dose_mg: 1200,
    timing: "morning",
    interactions: [],
    synergies: ["Racetams"],
    notes: "Same as Alpha-GPC (already in database). Best choline source for cognitive enhancement. Better than CDP-choline for acetylcholine production.",
    goals: ["focus"],
  },

  {
    name: "Phosphatidylethanolamine",
    aliases: ["pe", "cephalin"],
    category: "nootropic",
    evidence_tier: "weak",
    standard_dose_mg: 100,
    timing: "any",
    interactions: [],
    synergies: ["Phosphatidylserine", "Phosphatidylcholine"],
    notes: "Membrane phospholipid. Second most abundant after phosphatidylcholine. Limited supplementation research. Obtained from lecithin and eggs.",
    goals: ["focus", "longevity"],
  },

  {
    name: "Phosphatidylinositol",
    aliases: ["pi", "phosphoinositide"],
    category: "nootropic",
    evidence_tier: "weak",
    standard_dose_mg: 100,
    timing: "any",
    interactions: [],
    synergies: ["Inositol"],
    notes: "Membrane phospholipid and signaling molecule precursor. Part of inositol metabolism. Limited direct supplementation research.",
    goals: ["focus"],
  },

  {
    name: "DIM",
    aliases: ["diindolylmethane", "dim supplement"],
    category: "plant-extract",
    evidence_tier: "moderate",
    standard_dose_mg: 200,
    min_dose_mg: 100,
    max_dose_mg: 400,
    timing: "with-food",
    interactions: ["Tamoxifen", "Estrogen medications"],
    synergies: ["I3C"],
    notes: "From cruciferous vegetables. Modulates estrogen metabolism toward beneficial 2-hydroxy pathway. Take with fat. Microencapsulated form preferred.",
    goals: ["longevity", "inflammation"],
  },

  {
    name: "I3C",
    aliases: ["indole-3-carbinol", "indole 3 carbinol"],
    category: "plant-extract",
    evidence_tier: "moderate",
    standard_dose_mg: 300,
    min_dose_mg: 200,
    max_dose_mg: 600,
    timing: "with-food",
    interactions: ["Estrogen medications", "Tamoxifen"],
    synergies: ["DIM", "Sulforaphane"],
    notes: "Precursor to DIM from broccoli/cabbage/Brussels sprouts. Converts to DIM in stomach acid. Some prefer DIM for more stable dosing.",
    goals: ["longevity", "inflammation"],
  },

  {
    name: "Calcium D-Glucarate",
    aliases: ["calcium d-glucarate", "d-glucarate"],
    category: "supplement",
    evidence_tier: "weak",
    standard_dose_mg: 1500,
    min_dose_mg: 500,
    max_dose_mg: 3000,
    timing: "any",
    interactions: [],
    synergies: ["DIM", "I3C"],
    notes: "Supports glucuronidation detoxification pathway. May inhibit beta-glucuronidase enzyme. Limited human evidence. Often combined with DIM/I3C.",
    goals: ["longevity"],
  },

];
